= Raisa Kabir - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Mobilize
Mobilize is a desktop application built to help people organize their contacts and tasks. It is primarily written
in Java and uses the Object Oriented Paradigm. The user interacts with it using a CLI, and it has a GUI created with JavaFX.

*Code contributed*: [https://github.com/CS2103AUG2017-T11-B3/main/blob/master/collated/main/raisa2010.md[Functional code]] [https://github.com/CS2103AUG2017-T11-B3/main/blob/master/collated/test/raisa2010.md[Test code]]

=== Enhancement Added: Add Task

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=addtask]

#End of Extract#

---

==== Justification

The Add Task command was the first step in expanding Mobilize's capabilities. In
allowing users to add pending tasks to their application, Mobilize has adopted
the responsibility of organizing its user's life.

The Add Task uses a Natural Language Parsing Library, http://ocpsoft.org/prettytime/nlp/[PrettyTime],
in order to make it more user-friendly, by allowing task dates to be set using natural language dates
and times. This makes the command format of the application less rigid and increases its appeal to
potential users.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=addtask]

#End of Extract#

---

=== Enhancement Added: Edit Task

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=edittask]

#End of Extract#

---

==== Justification

Editing tasks is a natural extension of the add task feature

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=edittask]

#End of Extract#

---

=== Enhancement Added: Tag Multiple Contacts and Tasks

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=tagtask]

#End of Extract#

---

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=tag]

#End of Extract#

---

==== Justification

The rationale behind adding a special feature to add tags cumulatively, was primarily to open up a world of
possibilities of the tags themselves, to a user. Not only can they be used to effectively, yet easily organize contacts
and tasks - that too, by multiple parameters - but they can also be used to __link__ the two with the same tag
to keep track of tasks with which people are associated and vice versa. +

That being said, the caveat to consider was whether to create a new command or modify the edit command itself
to allow for tagging cumulatively. In the end, it was decided that separating the two would help achieve the goal
of helping users be better organized, as the edit function focuses solely on __replacing__ existing tags or removing
them altogether while the tag command serves to increment them. In addition, the flexible indexing for the tag command helps users tag their desired contact or task even if they make
some mistakes in typing the index unlike the edit command.

Overall the tag command achieves the application's purposes of organizing its user's life much more efficiently.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=tag]

#End of Extract#

---

=== Other contributions

* Added autocomplete feature using ControlsFX Library (Pull request https://github.com/CS2103AUG2017-T11-B3/main/pull/96[#96]).
* Discovered bug during trial acceptance testing (https://github.com/CS2103AUG2017-T09-B4/main/issues/103[Issue #103]).
* Rewrote large parts of the User Guide and Developer to enhance it (Pull Request https://github.com/CS2103AUG2017-T11-B3/main/pull/144[#144]) (Pull Request https://github.com/CS2103AUG2017-T11-B3/main/pull/112[#112]).
* Reviewed and edited the language and structure of all documentation.
* Generated SampleData.xml file (Pull Request https://github.com/CS2103AUG2017-T11-B3/main/pull/138[#138]).
* Set up organization, Milestones and Issues.
* Assisted other students in Slack.
